### ISSUE TITLE
Replace signalcoverage-share-3.0.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by mvdan** [locked-fg/signalcoverage#26]
You should import `signalcoverage-share-3.0.0-SNAPSHOT.jar` from a public maven repo (jcenter, mavenCentral) or build it from source like you do with ActionBarSherlock.

Also, you could ipmort ABS from a maven repo and that would be much easier than what you do now.

**Comment by locked-fg** [comment]
Thanks for the hint, you are right. Actually I am about to completely shut down the project. So - I don't know when and if I'm integrating the proposed changes.
